### ISSUE TITLE
npm run build时有个报错

### ISSUE THREAD

**Issue by mymutouren** [jaywcjlove/FED#66]
> fed@1.0.0 min:js /home/wwwroot/www.yiijj.com/page/www.yiijj.com.index
> uglifyjs js/index.js -o js/index.min.js

module.js:491
    throw err;
    ^

Error: Cannot find module '../tools/node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wwwroot/www.yiijj.com/page/www.yiijj.com.index/node_modules/.bin/uglifyjs:6:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fed@1.0.0 min:js: `uglifyjs js/index.js -o js/index.min.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fed@1.0.0 min:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jaywcjlove** [comment]
@mymutouren 我这里没有配置 `npm run build` 命令

如果只想编译 `node build/compile.js `   
`npm run deploy` 并提交到`gh-pages` 分支   
`npm run start` 编译并提交到`gh-pages` 分支    


....
